### ISSUE TITLE
Docusaurus

### ISSUE THREAD

**Issue by vinber** [MapContrib/test-tuto#2]
https://docusaurus.io/

**Comment by GuillaumeAmat** [comment]
Si tu veux je peux migrer ce repo sur Gitlab et mettre Docusaurus pour que tu puisses jouer avec (possible aussi sur Github mais vu qu'on migre MapContrib sur Gitlab...)

**Comment by vinber** [comment]
yes :)

**Comment by GuillaumeAmat** [comment]
SI ça te dit on peut aussi remplacer complètement le site actuel avec ça. Docusaurus permet de faire documentation + blog + pages de contenus.

Ça libèrerait un peu de place sur le serveur et stopperait les spammeurs pour de bon ;)

**Comment by vinber** [comment]
parfait,
et à terme on va tenter de bouger le serveur :) donc ok

on perd les quelqes pages du wordpress, à voir si peut rediriger !

et du coup après cela se gère avec du markdown ?
